kserve/modelmesh-runtime-adapter

- .github/workflows/build-and-push.yml
- .github/workflows/unit-test.yml
- CONTRIBUTING.md
- scripts/build_docker.sh
Updated the GitHub Action workflows that will now lint and test for PRs, and also, on a git push, lint+test, then build/push the new image to Docker Hub.
Misc fixes + Linting fixes are also included to pass the lint check.
> chore: Update GH Action workflows

- .github/workflows/build-and-push.yml
We want version tagged docker images to be pushed to DockerHub when a new release is tagged in GitHub.
Adjusted the workflow file to also test, build, and push the image on tags.
Tagged image versions on DockerHub.
> chore: Add GitHub Action release tag workflow

- model-mesh-triton-adapter/README.md
The `How to` in the triton adapter is not so clear and outdated. Update it to make it work.
model-mesh-triton-adapter/README.md
Users can test the Triton adapter locally now.
> docs(triton): update triton adapter docs to make it run

- model-serving-puller/puller/config.go
- model-serving-puller/puller/dotpath.go
- model-serving-puller/puller/dotpath_test.go
- model-serving-puller/puller/puller.go
- model-serving-puller/puller/puller_test.go
- model-serving-puller/testdata/storage-config/_test-default-type_serviceaccount_secrets
- model-serving-puller/testdata/storage-config/default_test-default-type
- model-serving-puller/testdata/storage-config/genericParameters
- pullman/config.go
- pullman/pullman_test.go
- pullman/storageproviders/http/provider_test.go
- pullman/storageproviders/s3/provider_test.go
This is related to the changes to support the new StorageSpec proposal discussed in [this Design Doc](https://docs.google.com/document/d/1rYNh93XNMRp8YaR56m-_zK3bqpZhhGKgpVbLPPsi-Ow/edit#heading=h.gb4md09ddljj). The changes include generalizing the storage config overrides to support more than just  changing the s3 bucket and defaulting the value for the storage key to support existing KServe style storage configurations.
- support general overriding of storage configurations from load model request (instead of just `bucket`)
- support a simple dotpath style for overriding storage parameters nested in a struct
- make `ModelKey.storage_key` optional in the request
- if no value for `ModelKey.storage_key` is specified in the request, check for a default storage key: `default` if no type …
> feat(puller): support new storage spec semantics and refactor tests

- model-serving-puller/puller/puller.go
We want to have the model puller support gcs and http storage types.
Import the gcs and http providers in the puller in order to register their types.
The model-serving-puller can now handle gcs and http types.
> chore: enable gcs and http in model puller

- model-serving-puller/puller/puller.go
- model-serving-puller/puller/puller_test.go
- model-serving-puller/server/server_test.go
When using the puller with non-builtin runtimes, the `modelType` provided in the Predictor is passed within some json in the `modelKey` field because the internal `modelType` field is used for model placement constraints (it's historical/unfortunate and we hope to change that soon).
However, after the recent storage-related refactor this separate `model_type` attribute is no longer being passed through.
Also, the `storage_key` and `storage_params` attributes _are_ passed along by the puller but this doesn't really make sense because they're consumed by the puller and intended to be abstracted away from the runtime.
- Ensure the `model_type` json attribute is passed through
- Remove `storage_key`, `storage_params` and bucket attributes from the transformed request
- Update unit tests to …
> fix: Include model_type in loadModel modelKey json passed by the puller

- model-mesh-mlserver-adapter/server/server.go
- model-mesh-triton-adapter/server/server.go
MLServer and Triton both support the ModelMetadata endpoint, so we should surface it for end users.
Here, the `ModelMetadata` endpoint is enabled in the adapter logic for MLServer and Triton.
Ref: https://github.com/kserve/modelmesh-serving/issues/136
> feat: Enable ModelMetadata endpoint

- model-serving-puller/puller/puller.go
Azure support was added in pullman. This enables its use in the puller sidecar.
> chore: Enable azure storage provider in puller

- model-mesh-ovms-adapter/server/const.go
- model-mesh-ovms-adapter/server/server.go
- model-mesh-triton-adapter/server/server.go
Intel's OpenVINO Model Server has historically only supported the v1 (TFS) prediction API, but may also support v2 in upcoming versions.
Adjust the built-in OVMS adapter to advertise the V2 gRPC Service APIs in addition to V1.
KServe V2 Inference API will work with OVMS in ModelMesh Serving once supported by the OVMS container.
> feat: Add V2 Inference API support for OVMS runtime

- model-mesh-mlserver-adapter/server/server.go
- model-mesh-ovms-adapter/server/server.go
- model-mesh-triton-adapter/server/server.go
- model-serving-puller/puller/puller.go
- model-serving-puller/puller/puller_test.go
- model-serving-puller/server/server.go
For some reason, the `LoadModel` context is not passed via the puller's `ProcessLoadModelRequest` function to pullman's `Pull` function. This means that storage downloads won't be cancelled when the corresponding request is cancelled or times out.
Add a `Context` argument to the puller's `ProcessLoadModelRequest` function, use in the call to pull manager's `Pull` instead of `context.TODO()`.
In-progress model downloads from shared storage downloads will be cancelled when the corresponding request is cancelled or times out.
> fix: Propagate context to puller download tasks

- internal/util/connect.go
- internal/util/connect_test.go
- internal/util/fileutil.go
- internal/util/loadmodel.go
- model-mesh-mlserver-adapter/main.go
- model-mesh-mlserver-adapter/server/adaptmodellayout_test.go
- model-mesh-mlserver-adapter/server/config.go
- model-mesh-mlserver-adapter/server/server.go
- model-mesh-ovms-adapter/main.go
- model-mesh-ovms-adapter/server/adaptmodellayout.go
- model-mesh-ovms-adapter/server/adaptmodellayout_test.go
- model-mesh-ovms-adapter/server/config.go
- model-mesh-ovms-adapter/server/server.go
- model-mesh-triton-adapter/main.go
- model-mesh-triton-adapter/server/adaptmodellayout.go
- model-mesh-triton-adapter/server/adaptmodellayout_test.go
- model-mesh-triton-adapter/server/config.go
- model-mesh-triton-adapter/server/server.go
- model-serving-puller/puller/puller.go
- model-serving-puller/server/modelstate.go
- model-serving-puller/server/server.go
While working on adding built-in adapter support for torchserve, I noticed various things to be added/tidied in the adapter logic.
Note that there's still a lot of simplification that could be done - in particular de-duplication and unification of common logic between the different adapters.
- Move logic for resolving gRPC endpoint from ServingRuntime endpoint into a utility function
- Change `adapterConfig.RootModelDir` to reference the subdir containing the _adapted_ model files/dirs
- Create the adapter model subdir when the adapter is first created
- Change the initial gRPC connection to the model server(s) to be non-blocking and remove connection test from that context - the `runtimeStatus` func will be called subsequently to determine when the connection/server is ready
- Add logic …
> tidy: Clean up various adapter/puller logic

- model-serving-puller/puller/puller.go
- pullman/storageproviders/pvc/provider.go
- pullman/storageproviders/pvc/provider_test.go
Add pullman PVC storage provider to support models in PVC
Want to serve models located in PVC storage
- Added a PVC storage provider to the pullman package.
- Updated the puller to check for PVC type and set up modelDir differently.
Pullman now supports pulling model files from PVC Storage
- https://github.com/kserve/modelmesh-serving/issues/230
- https://github.com/kserve/modelmesh-serving/pull/267
> feat: Add pullman PVC storage provider

- model-mesh-mlserver-adapter/server/adaptmodellayout_test.go
- model-mesh-mlserver-adapter/server/server.go
As documented in [this issue](https://github.com/kserve/modelmesh-runtime-adapter/issues/40), there is currently a bug in the conversion of the `uri` provided in the MLServer `model-settings.json` file if the model files are symlinked before the uri conversion occurs. This PR is intended to fix the issue by ensuring that `model-settings.json` will always be processed first.
The function `adaptModelLayoutForRuntime` in the MLServer adapter `server.go` was modified to ensure that, if present, the `model-settings.json` file will be placed at the head of the list of files to be processed. This makes sure that the config file will always be processed before any symlinks are created for the model files.
A unit test was also added to ensure that the bug was fixed.
Incorrect uri conversion bug no …
> fix: correct mlserver uri conversion regardless of filenames

- Dockerfile
Fix the multi-arch builds so that all binaries are built for the target OS/ARCH. Currently, only the `puller` is built for the target.
- export GOOS and GOARCH within multi-command RUN that builds the binaries
> fix: build all binaries for the target OS/ARCH

- model-serving-puller/puller/puller.go
- pullman/storageproviders/http/provider.go
- pullman/storageproviders/http/provider_test.go
Removes some buggy behavior related to the handling of an empty `modelPath` being passed into the puller
- use `filepath.Join()` instead of manual string concatenation with the file separator to handle an empty `modelPathFilename`
-  in the http storageProvider, remove duplication of the `localPath` into the rendered path
- just to not it: I think this bug has not been caught because using the HTTP provider with a `storageURI` means that the local path is empty
- this will need to be fixed before https://github.com/kserve/modelmesh-serving/pull/382 can be merged
- add check to ensure that the local path for files downloaded by the puller is always a path within the generated model dir (prevents the generated dir name from being the model file as was seen in …
> fix(puller): fixes related to an empty model path

- model-serving-puller/puller/puller.go
- model-serving-puller/puller/puller_test.go
Solving https://github.com/kserve/modelmesh-runtime-adapter/issues/54
Resolved symlinks (created by PVC puller) in order to calculate the target's' size instead of the symlink's size.
Relevant tests were modified to validate the new behavior.
Models' disk sizes (pulled from PVC) are evaluated correctly.
> Fixing model disk size evaluation for pvc

- Dockerfile
Update runtime image from `ubi8/ubi-minimal:8.7` to `ubi8/ubi-minimal:8.8`
> chore: Update runtime image from ubi8/ubi-minimal:8.7 to 8.8

- .github/workflows/codeql.yml
Add CodeQL configuration file to enable code vulnerability scans.
FYI @rafvasq @njhill
> chore: Add CodeQL configuration

- internal/envconfig/envconfig.go
- model-mesh-torchserve-adapter/server/config.go
Created function `GetEnvInt32` using `strconv.ParseInt` as recommended for accuracy in cases where `int32` is expected. Similar to [modelmesh-serving's #446](https://github.com/kserve/modelmesh-serving/pull/446)
- https://github.com/kserve/modelmesh-runtime-adapter/security/code-scanning/1
- https://github.com/kserve/modelmesh-runtime-adapter/security/code-scanning/2
> fix: Incorrect conversion between integer types

- Dockerfile
Build/test failures due to the wrong Python version.
Specify and link python38.
Working builds
> fix: Specify Python 3.8 in Dockerfile

- go.mod
- go.sum
chore: Fix Stack-based Buffer Overflow on protobuf on protobuf
- https://security.snyk.io/vuln/SNYK-GOLANG-GOOGLEGOLANGORGPROTOBUFENCODINGPROTOJSON-6137908
> chore: Upgrade google.golang.org/protobuf

- Dockerfile
- model-mesh-triton-adapter/scripts/tf_pb.py
chore:	Update python to 3.11 in preparation of UBI9 upgrade.
> Upgrade python to 3.11

- .pre-commit-config.yaml
- Dockerfile
- go.mod
chore:	Update Go lang from 1.21 to 1.22.9
Update golint-ci to 1.60.3 to be compatible with go1.22
Update base images from UBI8 to UBI9
> Update Go Lang and base iamges
